general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:8000'
    client: '500'
    abapCredentialsID: 'W11'
    repository: 'yury-permiakov-wrgcts21_1'
