general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'W11'
    repository: 'yury-permiakov-wrgcts21_1'
  gctsExecuteABAPUnitTests:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'W11'
    repository: 'yury-permiakov-wrgcts21_1'
 gctsRollback:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'W11'
    repository: 'yury-permiakov-wrgcts21_1'
